// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwR-QWtS-2QII-rq4iqF4oABu3uaK6jmM',
    appId: '1:489367839456:web:62c36b1b1352ae2cfca685',
    messagingSenderId: '489367839456',
    projectId: 'trip-planner-app-81431',
    authDomain: 'trip-planner-app-81431.firebaseapp.com',
    storageBucket: 'trip-planner-app-81431.firebasestorage.app',
    measurementId: 'G-DLC572HJVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACyMyhSbkG9zsg-N2MorOBiWSvBhmoaAw',
    appId: '1:489367839456:android:3a4fbb6729c6afc9fca685',
    messagingSenderId: '489367839456',
    projectId: 'trip-planner-app-81431',
    storageBucket: 'trip-planner-app-81431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUKXFLqTYWHc0d-_zsa96YUiZ8sbk9jE',
    appId: '1:489367839456:ios:253d8cf8918d30f5fca685',
    messagingSenderId: '489367839456',
    projectId: 'trip-planner-app-81431',
    storageBucket: 'trip-planner-app-81431.firebasestorage.app',
    iosBundleId: 'com.example.tripPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUKXFLqTYWHc0d-_zsa96YUiZ8sbk9jE',
    appId: '1:489367839456:ios:253d8cf8918d30f5fca685',
    messagingSenderId: '489367839456',
    projectId: 'trip-planner-app-81431',
    storageBucket: 'trip-planner-app-81431.firebasestorage.app',
    iosBundleId: 'com.example.tripPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwR-QWtS-2QII-rq4iqF4oABu3uaK6jmM',
    appId: '1:489367839456:web:b46255a15b560117fca685',
    messagingSenderId: '489367839456',
    projectId: 'trip-planner-app-81431',
    authDomain: 'trip-planner-app-81431.firebaseapp.com',
    storageBucket: 'trip-planner-app-81431.firebasestorage.app',
    measurementId: 'G-088HC645JN',
  );

}